import smtplib, ssl
from email.message import EmailMessage

from source.config_reader import ConfigReader 


class EmailDistributor(ConfigReader):
	'''
	
	Sends an emails to each recipient in the recipients list.

	All email parameters are defined in config.json expect the user's email
	password.  The email password is not in config.json for security reasons.


	'''
	def __init__(self):		
		super().__init__()



	# *************************************************************
	# Start: Public methods
	
	def send_emails(self, video_url, email_password):
		'''

		sends an email to each email address in the recipents list.

		email_password: if you are using gmail then your regular email
		password will not work. You have to sign into you google account
		and create an 'app password'. An app password is 16 letters/number
		generated by google.

		example google app password: epnimreisdtblmzb 


		'''


		for recipient in self.email_recipents:
			print("sending email to {}".format(recipient))

			self.send_email(
				recipient=recipient,
				video_url=video_url,
				email_password=email_password
			)



	# End: Public methods
	# *************************************************************   	


	# *************************************************************
	# Start: Private methods
	
	def send_email(self, recipient, video_url, email_password):
		'''
		
		sends an email to one person


		'''

		# initializations:
		port = self.email_server_port  # For SSL
		smtp_server = self.email_server
		sender_email = self.email_sender  # Enter your address
		receiver_email = recipient  # Enter receiver address
		password = email_password

		# Build the email message:
		msg = EmailMessage()
		msg.set_content(self.email_body.format(video_url))
		msg['Subject'] = self.email_subject
		msg['From'] = sender_email
		msg['To'] = receiver_email

		# Login to the server and send the email:
		context = ssl.create_default_context()
		with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
		    server.login(sender_email, password)
		    server.send_message(msg, from_addr=sender_email, to_addrs=receiver_email)











	# End: Private methods
	# *************************************************************   